# Белый список: окна времени, в которые разрешено проведение работ в каждой из зон доступности.
white_list:
  Zone_1: #zoneId
    - start_hour: 1 # кратно часу от 0 до 23
      end_hour: 5 # кратно часу от 0 до 23
  Zone_2: #zoneId
    - start_hour: 23 # кратно часу от 0 до 23
      end_hour: 6 # кратно часу от 0 до 23
  Zone_3: #zoneId
    - start_hour: 2 # кратно часу от 0 до 23
      end_hour: 4 # кратно часу от 0 до 23
  Zone_4: #zoneId
    - start_hour: 23 # кратно часу от 0 до 23
      end_hour: 6 # кратно часу от 0 до 23
# Черный список: зоны доступности, в которых проведения любых работ кроме критичных полностью запрещено (имеет приоритет над белым списком).
black_list: []
# Количество зон доступности, для которых в любой момент времени гарантировано, что в них не проводится никаких работ 
# (зоны доступности из черного списка никогда не удовлетворяют этому условию).
min_avialable_zones: 1
# * Паузы для каждой из зон доступности между работами, которые в ней будут проводиться.
pauses: {}
# Минимальная длительность работ: 5 минут для автоматических и 30 минут для ручных. 
min_work_duration_minutes:
  automatic: 5
  manual: 30
# Максимальная длительность работ - 6 часов, для обычных работ любого типа и без ограничений для критических. 
max_work_duration_minutes: # only for regular, not for critical works
  automatic: 360
  manual: 360
# Дедлайн не может превышать текущую дату более, чем на 4 недели. Желаемое время начала ручных работ кратно 5 минутам, автоматических - 1 минуте. 
max_deadline_days: 28
# Процент сжимаемости для автоматических работ - от 0% до 99%, но сжимать меньше минимальной длительности нельзя, ручние работы не сжимаются!
time_compression_percents: 90% # only for automatic works
